config/routes.rb
Rails.application.routes.draw do
  resources :g_models, only: [:show, :index, :new, :create]
  resources :guitars, only: [:new, :create, :edit, :update]
  root 'static_pages#home'

end

app/models/g_model.rb
class GModel < ActiveRecord::Base
  has_many :guitars
end

app/models/guitar.rb
class Guitar < ActiveRecord::Base
  belongs_to :g_model
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/g_models_controller.rb
class GModelsController < ApplicationController

  def index
     @models = GModel.all
  end

  def show
    @model = GModel.find_by_id(params[:id])
    if @model
      @guitars = @model.guitars.order('name ASC').page(params[:page])
      render 'show'
    else
      redirect_to '/404.html'
    end
  end

  def new
    @model = GModel.new
  end

  def create
    @model = GModel.create(model_params)
    @model.save
    if @model.save
      redirect_to root_url
    else
      render 'new'
    end

  end

  private

  def model_params
    params.require(:g_model).permit(:name)
  end

end

app/controllers/guitars_controller.rb
class GuitarsController < ApplicationController

  def new
    @guitar = Guitar.new
  end

  def create
    @guitar = Guitar.create(guitar_params)
    @guitar.save
    if @guitar.save
      redirect_to root_url
    else
      render 'new'
    end

  end

  def edit
    @guitar = Guitar.find_by_id(params[:id])
    if @guitar
      render 'edit'
    else
      redirect_to root_url
    end
  end

  def update
    @guitar = Guitar.find_by_id(params[:id])
    @guitar.update_attributes(guitar_params)
    if @guitar.update_attributes(guitar_params)
      redirect_to root_url
    else
      render 'edit'
    end
  end

  private

  def guitar_params
    params.require(:guitar).permit(:name, :g_model_id)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/g_models/index.html.erb
<h1>Гитары</h1>
<ul class="nav nav-tabs">
      <li><%= link_to "Главная", root_url %></li>
      <li class="active">
        <%= link_to "Гитары" %>
      </li>
      <li><%= link_to "Бас-гитары" %></li>
      <li><%= link_to "Информация" %></li>
      <li><%= link_to "Форум" %></li>
</ul>
<ul style="list-style-type:none">
    <% @models.each do |model| %>
      <li>
        <%= link_to(model) do %>
            <%= model.name %>
        <% end %>

      </li>
    <% end %>
 </ul>
<%= link_to "Добавить новую модель", new_g_model_path %>

app/views/g_models/new.html.erb
<h1>Добавить новую модель гитар</h1>
<%= form_for @model do |f| %>
<%= f.label 'Название модели' %>
<%= f.text_field :name %>
<%= f.label ':  ' %>
<%= f.submit 'Create model' %>
<% end %>

app/views/g_models/show.html.erb
<% if @model.guitars.any? %>
    <ul style="list-style-type:none">
        <% @guitars.each do |g| %>
            <li>
                <%= g.name %>
                <%= link_to "Редактировать", edit_guitar_path(g) %>
            </li>
        <% end %>
    </ul>
<% end %>
<%= link_to "Добавить новую гитару", new_guitar_path %>

app/views/guitars/edit.html.erb
<h1>Редактировать информацию о гитаре</h1>
<%= form_for @guitar do |f| %>
<%= f.label 'Название гитары' %>
<%= f.text_field :name %>
<%= f.label 'ID модели' %>
<%= f.text_field :g_model_id %>
<%= f.label ':  ' %>
<%= f.submit 'Update guitar' %>
<% end %>

app/views/guitars/new.html.erb
<h1>Добавить новую гитару</h1>
<%= form_for @guitar do |f| %>
<%= f.label 'Название гитары' %>
<%= f.text_field :name %>
<%= f.label 'ID модели' %>
<%= f.text_field :g_model_id %>
<%= f.label ':  ' %>
<%= f.submit 'Create guitar' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyGuitarApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<h1>Домашняя страница</h1>

<ul class="nav nav-tabs">
      <li class="active">
        <%= link_to "Главная" %>
      </li>
      <li><%= link_to "Гитары", g_models_path %></li>
      <li><%= link_to "Бас-гитары" %></li>
      <li><%= link_to "Информация" %></li>
      <li><%= link_to "Форум" %></li>
</ul>